#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

if (class_exists(Dotenv\Dotenv::class)) {
    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
    $dotenv->safeLoad();
}

$kernel = new \App\Console\Kernel();
$kernel->handle();
